# Configuration for CircleCI

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.6
      
    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4
    branches:
      ignore:
        - gh-pages

    steps:
      - checkout
